myblogapp/myblogapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls)
]

myblogapp/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),	
]

myblogapp/posts/models.py
import datetime

from django.db import models
from django.utils import timezone

#class Question(models.Model):
#    question_text = models.CharField(max_length=200)
#    pub_date = models.DateTimeField('date published')
#    def __str__(self):
#    	return self.question_text
#    def was_published_recently(self):
#        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

# Create your models here.
class Post(models.Model):
	post_title = models.CharField(max_length=100)
	pub_date = models.DateTimeField('date published')
	image = models.ImageField(upload_to = 'posts')
	body = models.TextField()
	def __str__(self):
		return self.post_title
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

myblogapp/posts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Post

#from django.shortcuts import render
#from django.http import HttpResponse

# Create your views here.

class IndexView(generic.ListView):
	"""docstring for IndexView"""
	template_name = 'posts/index.html'
	context_object_name = 'latest_post_list'

	def get_queryset(self):
		return Post.objects.order_by('-pub_date')[:]

class DetailView(generic.DetailView):
	"""docstring for DetailView"""
	model = Post
	template_name = 'posts/detail.html'

myblogapp/posts/templates/posts/detail.html
{% load static %}

<!DOCTYPE html>
<html lang = "ja-jp">
<head>
    <title>HAiK Health Care</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">
    <link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
</head>

<body>
	<div class="page-header">
		<h1><a href="">{{ post.post_title }}</a></h1>
	</div>
	<div class="content container">
		<div "row">
			<div class="col-md-8">
				<div class="post">
					<div class="date">
						{{ post.pub_date }}
					</div>
					<p>{{ post.body }}</p>
				</div>
			</div>
		</div>
	</div>
</body>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>>{% endif %}
</html>

myblogapp/posts/templates/posts/index.html
{% load static %}

<!DOCTYPE html>
<html lang = "ja-jp">
<head>
    <title>HAiK Health Care</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">
    <link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
</head>
<body>
	<div class="page-header">
		<h1><a href="/">Haik Health Care blog</a></h1>
	</div>
		<div class="content container">
			<div "row">
				<div class="col-md-8">
					{% if latest_post_list %}
						{% for post in latest_post_list %}
							<div class="post">
								<h1><a href="{% url 'posts:detail' post.id %}">{{ post.post_title }}</a></h1>
								<div class="date">
									{{ post.pub_date }}
								</div>
								<p>{{ post.body|linebreaks }}</p>
							</div>
						{% endfor %}
					{% else %}
				</div>
			</div>
		</div>
		<p>No posts are available.</p>
	{% endif %}
</body>
</html>